// <auto-generated />
using System;
using Fosol.Schedule.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fosol.Schedule.DAL.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20181014041721_v01.00.00")]
    partial class v010000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fosol.Schedule.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("Key");

                    b.Property<int>("Kind");

                    b.Property<int>("OwnerId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int>("SubscriptionId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Privileges");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountUser", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("UserId");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUsers");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("EventId");

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime?>("StartDate");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("EventId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ActivityCriteria", b =>
                {
                    b.Property<int>("ActivityId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("ActivityId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("ActivityCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Address2")
                        .HasMaxLength(150);

                    b.Property<int>("Category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DataType");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarAttribute", b =>
                {
                    b.Property<int>("CalendarId");

                    b.Property<int>("AttributeId");

                    b.HasKey("CalendarId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("CalendarAttributes");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarCriteria", b =>
                {
                    b.Property<int>("CalendarId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("CalendarId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("CalendarCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Type");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CriteriaObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Criteria")
                        .IsRequired();

                    b.Property<bool>("IsGroup");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CalendarId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("EndOn")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("StartOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("TagKey");

                    b.Property<string>("TagValue");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("CalendarId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("TagKey", "TagValue");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventCriteria", b =>
                {
                    b.Property<int>("EventId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("EventId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("EventCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventTag", b =>
                {
                    b.Property<int>("EventId");

                    b.Property<string>("TagKey");

                    b.Property<string>("TagValue");

                    b.HasKey("EventId", "TagKey", "TagValue");

                    b.HasIndex("TagKey", "TagValue");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Opening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ApplicationProcess");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<Guid>("Key");

                    b.Property<int>("MaxParticipants");

                    b.Property<int>("MinParticipants");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("OpeningType");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Openings");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningCriteria", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("OpeningId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("OpeningCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningParticipant", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("ParticipantId");

                    b.HasKey("OpeningId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("OpeningParticipants");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningParticipantApplication", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("ParticipantId");

                    b.HasKey("OpeningId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("OpeningParticipantApplications");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("AddressId");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<int>("CalendarId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("Gender");

                    b.Property<Guid>("Key");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("AddressId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantAddress", b =>
                {
                    b.Property<int>("ParticipantId");

                    b.Property<int>("AddressId");

                    b.HasKey("ParticipantId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("ParticipantAddresses");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantAttribute", b =>
                {
                    b.Property<int>("ParticipantId");

                    b.Property<int>("AttributeId");

                    b.HasKey("ParticipantId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ParticipantAttributes");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantContactInfo", b =>
                {
                    b.Property<int>("ParticipantId");

                    b.Property<int>("ContactInfoId");

                    b.HasKey("ParticipantId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("ParticipantContactInfos");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Tag", b =>
                {
                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Key", "Value");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<Guid>("Key");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAccountRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AccountRoleId");

                    b.HasKey("UserId", "AccountRoleId");

                    b.HasIndex("AccountRoleId");

                    b.ToTable("UserAccountRoles");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAddress", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AddressId");

                    b.HasKey("UserId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserContactInfo", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ContactInfoId");

                    b.HasKey("UserId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("UserContactInfos");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserInfo", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("Description");

                    b.Property<string>("FirstName");

                    b.Property<int?>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("UserId");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Account", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "Owner")
                        .WithMany("OwnedAccounts")
                        .HasForeignKey("OwnerId");

                    b.HasOne("Fosol.Schedule.Entities.Subscription", "Subscription")
                        .WithMany("Accounts")
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountRole", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Roles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountUser", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Activity", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany("Activities")
                        .HasForeignKey("EventId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ActivityCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Activity", "Activity")
                        .WithMany("Criteria")
                        .HasForeignKey("ActivityId");

                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Address", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Attribute", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User")
                        .WithMany("Attributes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Calendar", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarAttribute", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Attributes")
                        .HasForeignKey("CalendarId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Criteria")
                        .HasForeignKey("CalendarId");

                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ContactInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CriteriaObject", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Event", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Events")
                        .HasForeignKey("CalendarId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.Tag")
                        .WithMany("Events")
                        .HasForeignKey("TagKey", "TagValue");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany("Criteria")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventTag", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId");

                    b.HasOne("Fosol.Schedule.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagKey", "TagValue")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Opening", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Activity", "Activity")
                        .WithMany("Openings")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Criteria")
                        .HasForeignKey("OpeningId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningParticipant", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Participants")
                        .HasForeignKey("OpeningId");

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningParticipantApplication", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Applications")
                        .HasForeignKey("OpeningId");

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Participant", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Address")
                        .WithMany("Participants")
                        .HasForeignKey("AddressId");

                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Participants")
                        .HasForeignKey("CalendarId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantAddress", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany("Addresses")
                        .HasForeignKey("ParticipantId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantAttribute", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany("Attributes")
                        .HasForeignKey("ParticipantId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantContactInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.ContactInfo", "ContactInfo")
                        .WithMany("ParticipantContactInfos")
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany("ContactInfos")
                        .HasForeignKey("ParticipantId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Subscription", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Tag", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.User", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAccountRole", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.AccountRole", "AccountRole")
                        .WithMany("Users")
                        .HasForeignKey("AccountRoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAddress", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserContactInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.ContactInfo", "ContactInfo")
                        .WithMany("UserContactInfos")
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("ContactInformation")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithOne("Info")
                        .HasForeignKey("Fosol.Schedule.Entities.UserInfo", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
