// <auto-generated />
using System;
using Fosol.Schedule.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fosol.Schedule.DAL.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    partial class ScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fosol.Schedule.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("BusinessAddressId");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(25);

                    b.Property<string>("Email")
                        .HasMaxLength(150);

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(25);

                    b.Property<Guid>("Key");

                    b.Property<int>("Kind");

                    b.Property<int>("OwnerId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int>("SubscriptionId");

                    b.Property<string>("TollFreeNumber")
                        .HasMaxLength(25);

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("BusinessAddressId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("OwnerId", "State");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Privileges");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique();

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountUser", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("UserId");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUsers");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CriteriaRule");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("EndOn");

                    b.Property<int>("EventId");

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartOn");

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("EventId", "State", "StartOn", "EndOn", "CriteriaRule", "Name");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ActivityCriteria", b =>
                {
                    b.Property<int>("ActivityId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("ActivityId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("ActivityCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ActivityTag", b =>
                {
                    b.Property<int>("ActivityId");

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("ActivityId", "Key", "Value");

                    b.ToTable("ActivityTags");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Address1")
                        .HasMaxLength(150);

                    b.Property<string>("Address2")
                        .HasMaxLength(150);

                    b.Property<string>("City")
                        .HasMaxLength(150);

                    b.Property<string>("Country")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20);

                    b.Property<string>("Province")
                        .HasMaxLength(150);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Country", "Province", "City", "PostalCode");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Key", "Value");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CriteriaRule");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Name", "State", "CriteriaRule");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarCriteria", b =>
                {
                    b.Property<int>("CalendarId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("CalendarId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("CalendarCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarTag", b =>
                {
                    b.Property<int>("CalendarId");

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("CalendarId", "Key", "Value");

                    b.ToTable("CalendarTags");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Type");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Name", "Category", "Value");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CriteriaObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Statement")
                        .IsRequired();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CalendarId");

                    b.Property<int>("CriteriaRule");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("EndOn")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int?>("ParentEventId");

                    b.Property<int>("Repetition");

                    b.Property<DateTime?>("RepetitionEndOn");

                    b.Property<int>("RepetitionSize");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("StartOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ParentEventId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("CalendarId", "State", "StartOn", "EndOn", "CriteriaRule", "Name");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventCriteria", b =>
                {
                    b.Property<int>("EventId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("EventId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("EventCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventTag", b =>
                {
                    b.Property<int>("EventId");

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("EventId", "Key", "Value");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OauthAccount", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("Email")
                        .HasMaxLength(150);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("UserId", "Email");

                    b.HasIndex("AddedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("OauthAccounts");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Opening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ApplicationProcess");

                    b.Property<int>("CriteriaRule");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<Guid>("Key");

                    b.Property<int>("MaxParticipants");

                    b.Property<int>("MinParticipants");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("OpeningType");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ActivityId", "State", "CriteriaRule", "OpeningType", "ApplicationProcess", "Name");

                    b.ToTable("Openings");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningAnswer", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("QuestionId");

                    b.Property<int>("ParticipantId");

                    b.Property<int?>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Text")
                        .HasMaxLength(1000);

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("OpeningId", "QuestionId", "ParticipantId");

                    b.HasIndex("AddedById");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("OpeningId", "ParticipantId");

                    b.ToTable("OpeningAnswers");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningAnswerQuestionOption", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("QuestionId");

                    b.Property<int>("ParticipantId");

                    b.Property<int>("QuestionOptionId");

                    b.HasKey("OpeningId", "QuestionId", "ParticipantId", "QuestionOptionId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("OpeningAnswerQuestionOptions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningCriteria", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("CriteriaId");

                    b.HasKey("OpeningId", "CriteriaId");

                    b.HasIndex("CriteriaId");

                    b.ToTable("OpeningCriteria");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningParticipant", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("ParticipantId");

                    b.Property<int?>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("OpeningId", "ParticipantId");

                    b.HasIndex("AddedById");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("State");

                    b.HasIndex("UpdatedById");

                    b.ToTable("OpeningParticipants");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningQuestion", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<int>("QuestionId");

                    b.HasKey("OpeningId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("OpeningQuestions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningTag", b =>
                {
                    b.Property<int>("OpeningId");

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("OpeningId", "Key", "Value");

                    b.ToTable("OpeningTags");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<int>("CalendarId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("Gender");

                    b.Property<int?>("HomeAddressId");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(25);

                    b.Property<Guid>("Key");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100);

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(25);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserId");

                    b.Property<int?>("WorkAddressId");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("HomeAddressId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkAddressId");

                    b.HasIndex("CalendarId", "DisplayName")
                        .IsUnique();

                    b.HasIndex("Email", "State");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantAttribute", b =>
                {
                    b.Property<int>("ParticipantId");

                    b.Property<int>("AttributeId");

                    b.Property<int?>("AttributeId1");

                    b.HasKey("ParticipantId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("AttributeId1");

                    b.ToTable("ParticipantAttributes");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantContactInfo", b =>
                {
                    b.Property<int>("ParticipantId");

                    b.Property<int>("ContactInfoId");

                    b.HasKey("ParticipantId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("ParticipantContactInfo");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OpeningId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Sequence");

                    b.Property<int>("Trigger");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("OpeningId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("OpeningActions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("AllowOther");

                    b.Property<int>("AnswerType");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsRequired");

                    b.Property<int>("MaxLength");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Sequence");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddedById");

                    b.HasIndex("IsRequired");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("QuestionId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Sequence");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("EndOn")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("StartOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Name", "State");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ScheduleEvent", b =>
                {
                    b.Property<int>("ScheduleId");

                    b.Property<int>("EventId");

                    b.HasKey("ScheduleId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("ScheduleEvents");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<Guid>("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Name", "State");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DefaultAccountId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<Guid>("Key");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("DefaultAccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("State");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAccountRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AccountRoleId");

                    b.HasKey("UserId", "AccountRoleId");

                    b.HasIndex("AccountRoleId");

                    b.ToTable("UserAccountRoles");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAttribute", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AttributeId");

                    b.Property<int?>("AttributeId1");

                    b.HasKey("UserId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("AttributeId1");

                    b.ToTable("UserAttributes");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserContactInfo", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ContactInfoId");

                    b.HasKey("UserId", "ContactInfoId");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("UserContactInfo");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserInfo", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Birthdate");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("Gender");

                    b.Property<int?>("HomeAddressId");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100);

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(25);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("WorkAddressId");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(25);

                    b.HasKey("UserId");

                    b.HasIndex("AddedById");

                    b.HasIndex("HomeAddressId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("WorkAddressId");

                    b.HasIndex("LastName", "FirstName", "Gender");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserSetting", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.Property<int>("AddedById");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("UserId", "Key");

                    b.HasIndex("AddedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Key", "Value");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Account", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Address", "BusinessAddress")
                        .WithMany()
                        .HasForeignKey("BusinessAddressId");

                    b.HasOne("Fosol.Schedule.Entities.User", "Owner")
                        .WithMany("OwnedAccounts")
                        .HasForeignKey("OwnerId");

                    b.HasOne("Fosol.Schedule.Entities.Subscription", "Subscription")
                        .WithMany("Accounts")
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountRole", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Roles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.AccountUser", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Activity", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany("Activities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ActivityCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Activity", "Activity")
                        .WithMany("Criteria")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ActivityTag", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Activity", "Activity")
                        .WithMany("Tags")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Address", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Attribute", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Calendar", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Calendars")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Criteria")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CalendarTag", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Tags")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ContactInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.CriteriaObject", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Event", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Events")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Event", "ParentEvent")
                        .WithMany()
                        .HasForeignKey("ParentEventId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany("Criteria")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.EventTag", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OauthAccount", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("OauthAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Opening", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Activity", "Activity")
                        .WithMany("Openings")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningAnswer", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany()
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");

                    b.HasOne("Fosol.Schedule.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.OpeningParticipant", "OpeningParticipant")
                        .WithMany("Answers")
                        .HasForeignKey("OpeningId", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.OpeningQuestion", "OpeningQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("OpeningId", "QuestionId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningAnswerQuestionOption", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany()
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");

                    b.HasOne("Fosol.Schedule.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.QuestionOption", "Option")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId");

                    b.HasOne("Fosol.Schedule.Entities.OpeningAnswer", "OpeningAnswer")
                        .WithMany("Options")
                        .HasForeignKey("OpeningId", "QuestionId", "ParticipantId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningCriteria", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.CriteriaObject", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Criteria")
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningParticipant", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Participants")
                        .HasForeignKey("OpeningId");

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany("Openings")
                        .HasForeignKey("ParticipantId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningQuestion", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Questions")
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.OpeningTag", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Tags")
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Participant", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Calendar", "Calendar")
                        .WithMany("Participants")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Address", "HomeAddress")
                        .WithMany()
                        .HasForeignKey("HomeAddressId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Address", "WorkAddress")
                        .WithMany()
                        .HasForeignKey("WorkAddressId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantAttribute", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Attribute")
                        .WithMany("Participants")
                        .HasForeignKey("AttributeId1");

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany("Attributes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ParticipantContactInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.ContactInfo", "ContactInfo")
                        .WithMany("Participants")
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Participant", "Participant")
                        .WithMany("ContactInfo")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Process", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Opening", "Opening")
                        .WithMany("Actions")
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Question", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Questions")
                        .HasForeignKey("AccountId");

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.QuestionOption", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Schedule", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Account", "Account")
                        .WithMany("Schedules")
                        .HasForeignKey("AccountId");

                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.ScheduleEvent", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Schedule", "Schedule")
                        .WithMany("Events")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.Subscription", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.User", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Account", "DefaultAccount")
                        .WithMany()
                        .HasForeignKey("DefaultAccountId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAccountRole", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.AccountRole", "AccountRole")
                        .WithMany("Users")
                        .HasForeignKey("AccountRoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserAttribute", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Attribute")
                        .WithMany("Users")
                        .HasForeignKey("AttributeId1");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Attributes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserContactInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.ContactInfo", "ContactInfo")
                        .WithMany("Users")
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("ContactInformation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserInfo", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.Address", "HomeAddress")
                        .WithMany()
                        .HasForeignKey("HomeAddressId");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithOne("Info")
                        .HasForeignKey("Fosol.Schedule.Entities.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fosol.Schedule.Entities.Address", "WorkAddress")
                        .WithMany()
                        .HasForeignKey("WorkAddressId");
                });

            modelBuilder.Entity("Fosol.Schedule.Entities.UserSetting", b =>
                {
                    b.HasOne("Fosol.Schedule.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Fosol.Schedule.Entities.User", "User")
                        .WithMany("Settings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
